### ISSUE TITLE
Choose a Python library for modbus communication.

### ISSUE THREAD

**Issue by wkitka** [synchrotron-solaris/dev-solaris-adam#1]
Proposed start point: https://stackoverflow.com/questions/17081442/python-modbus-library

**Comment by Patfra** [comment]
Are we using Modbus TCP, Modbus over TCP or different type of Modbus protocol?
 I ask about that, because on the proposed site I have found information, which states that:
- **modbus-tk** is the best option for RTU/TCP connection, but supports only them, 
- **pymodbus** provides support for TCP, UDP, Serial ASCII, Serial RTU, and Serial Binary
I reject **MinimalModbus**, because it has bad performance when there are many units in the network

**Comment by wkitka** [comment]
[It looks like ADAM devices from other issues are using Modbus TCP.](http://www.advantech.com/products/ethernet-i-o-modules-with-daisy-chain-adam-6200/sub_7447e150-338d-402d-b5a1-c9ce6d98816e)

**Comment by LJBD** [comment]
Yeah, I think that if modbus-tk is sufficient, we can go for it. You might also try to connect to a real ADAM device and then check if you have any preferences when it comes to API of either library.
